panel.name=TMP-Network Panel

# Format:
# server.<name>=<folder>,<jar>,<port>

server.Hub=Hub,paper.jar,25566
server.PVP=PVP,paper.jar,25567
server.SMP=SMP,paper.jar,25568
server.Creative=Creative,paper.jar,25569
server.Freeop=Freeop,paper.jar,25570
server.Proxy=.,velocity.jar,25565

# Memory settings
ram.min=1G
ram.max=2G